CC = gcc
CFLAGS = -Wall
READER_OBJFILES = src/map_reader.o src/memory_region.o
WRITER_OBJFILES = src/map_writer.o src/memory_region.o
READER_TARGET = bin/map_reader
WRITER_TARGET = bin/map_writer

all: $(WRITER_TARGET) $(READER_TARGET)

run_reader: $(READER_TARGET)
	$(READER_TARGET)

run_writer: $(WRITER_TARGET)
	$(WRITER_TARGET)

$(READER_TARGET): $(READER_OBJFILES)
	$(CC) $(CFLAGS) -o $(READER_TARGET) $(READER_OBJFILES)

$(WRITER_TARGET): $(WRITER_OBJFILES)
	$(CC) $(CFLAGS) -o $(WRITER_TARGET) $(WRITER_OBJFILES)

clean:
	rm -f $(READER_OBJFILES) $(READER_TARGET) $(WRITER_OBJFILES) $(WRITER_TARGET)
